import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import UserInfoProvider from "@/components/provider/UserInfoProvider";
import { ReactQueryProvider } from "@/components/provider/ReactQueryProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"h-screen max-w-[390px] mx-auto flex flex-col"}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <UserInfoProvider>{children}</UserInfoProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
